version: 1.0

apis:
  - name: CacheTest   # <-- only extract the dev API
    # optional: id can be used, but name is enough if unique

output:
  folder: extracted
  format: yaml

options:
  includeProducts: true        # subscriptions tied to products
  includePolicies: false
  includeNamedValues: true
