openapi: 3.0.1
info:
  title: SAS_API_Entra
  description: ''
  version: '1.0'
servers:
  - url: https://cdngmnks-apim-dev.azure-api.net/sas-api-entra
paths:
  /crm/v2/applications:
    get:
      summary: Applications
      operationId: applications
      responses:
        '200':
          description: ''
  /oauth/token:
    post:
      summary: Token
      operationId: token
      responses:
        '200':
          description: ''
  /api/create:
    get:
      summary: create
      operationId: create
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]